### ISSUE TITLE
Faire maigrir le _package_ pour le mettre sur le CRAN

### ISSUE THREAD

**Issue by oliviermeslin** [InseeFrLab/DoReMIFaSolData#5]
Suite à une discussion avec @py-b, il apparaît qu'il serait beaucoup plus simple pour la diffusion d'`utilitR` que `doremifasolData` soit disponible sur le CRAN. Cela pose deux questions:

- La taille du _package_;
- Qui assure la maintenance.

## La taille du _package_

Le _package_ fait plusieurs dizaines de Mo, alors que le CRAN plafonne la taille des _packages_ à 5 Mo.

> As a general rule, neither data nor documentation should exceed 5MB (which covers several books). A CRAN package is not an appropriate way to distribute course notes, and authors will be asked to trim their documentation to a maximum of 5MB ([source](https://cran.r-project.org/web/packages/policies.html))

La solution consiste à réduire le nombre de tables disponibles dans le _package_. Il apparaît que les exemples d'`utilitR` n'utilisent que les tables suivantes : `filosofi_com_2016`, `filosofi_epci_2016`, `bpe_ens_2018`,  `cog_com_2019`. Or, ces quatre tables ne dépassent pas 3 Mo ensemble. **Je propose donc qu'on restreigne le _package_ à ces quatre tables**, et qu'on soit attentif à l'avenir à n'intégrer que de petites tables au _package_.

## Maintenance du _package_

Je propose de prendre contact avec Benoît et Romain pour voir à qui on attribue (temporairement s'il le faut) la maintenance du _package_.

**Comment by py-b** [comment]
L'idée générale me semble très bonne.

> Je propose de prendre contact avec Benoît et Romain pour voir à qui on attribue (temporairement s'il le faut) la maintenance du package.

Pour la maintenance, c'est automatiquement le _createur_ du package tel que défini dans DESCRIPTION. Donc pour l'instant c'est Pierre qui sera le destinataire des messages du CRAN pour une éventuelle maintenance. Je peux aussi assumer ce rôle si besoin. Tu voyais qui d'autre, @oliviermeslin ?

Autre point à prendre en considération : on ne peut pas soumettre des correctifs trop souvent. Le CRAN recommande d'espacer d'au moins 1 à 2 mois les soumissions. Plus possible d'ajouter un jeu de données avec autant de souplesse.

**Comment by oliviermeslin** [comment]
Après discussion avec Pierre, il semble que le sujet ne soit pas mûr, notamment parce qu'à l'Insee la politique sur la maintenance des _packages_ internes mis à disposition sur le CRAN n'est pas encore établie. Je propose _a minima_ qu'on allège le _package_, en ne gardant que les quatre tables que j'ai mentionnées. @py-b: est-ce que ça te convient?

**Comment by py-b** [comment]
Ok pour la suppression de tables.

@oliviermeslin : il ne faut pas garder aussi `data_iris_paris_2017` que tu as ajoutée récemment ?

_HS  : à vrai dire, je ne vois pas trop quelle peut être une autre politique de maintenance que de dire "les auteurs sont les plus à même de maintienir le package". Se renseigner par exemple sur la politique de maintenance de ce package ? https://CRAN.R-project.org/package=insee_

**Comment by oliviermeslin** [comment]
Ah oui bien sûr, il faut garder `data_iris_paris_2017 `!

**Comment by py-b** [comment]
J'en profiterais bien au passage pour rendre le nom cohérent : `data_iris_paris2017` -> `data_iris_paris_2017`
@oliviermeslin : tu penseras à faire la modif correspondante dans utilitR.

**Comment by RLesur** [comment]
Voici ce qu'on essaie de mettre en place pour la publication sur le CRAN :

- une équipe (= une division) souhaite publier sur le CRAN
- c'est cette division qui sera responsable de la maintenance
- en général, le mainteneur est l'auteur du package

Avant publication, on s'assure d'avoir l'accord au moins du chef de département et c'est cet accord qui engage la publication par l'Insee.

Pour DoReMiFaSolData, c'est différent car il n'y a pas d'équipe à proprement parler. Mais on peut considérer que c'est dans le cadre d'UtilitR. Il me semble que le go pour la publication sur le CRAN pourrait être donné par les sponsors.

**Comment by oliviermeslin** [comment]
@py-b : ok.

@RLesur : on va en parler à la prochaine réunion avec les sponsors.

**Comment by linogaliana** [comment]
@oliviermeslin tu n'avais pas oublié quelque chose ? cf. https://github.com/InseeFrLab/utilitR/commit/8331081bdcc99772cd8b48ffdefc47cb9905517f

**Comment by oliviermeslin** [comment]
Ah si...

**Comment by py-b** [comment]
@linogaliana :
@oliviermeslin a bien fait la modif ! https://github.com/InseeFrLab/utilitR/commit/062c1a8ae13e076f2bca08aa5add9826a39ea1f9

**Comment by linogaliana** [comment]
Ah oui j'étais trop impatient de me moquer de la mémoire défaillante d' @oliviermeslin , j'en ai oublié de faire pull avant de merger master. Au moins, je me console en me disant qu' il a oublié qu'il avait fait la modif
